apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment-list
spec:
  replicas: 5
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: ianodad/watchlistclient
          ports:
            - containerPort: 80